import { QueryClient } from "@tanstack/react-query"
import MenuTemplate from "../components/Menu/Menu"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <MenuTemplate />
        </header>
        {children}
      </body>
    </html>
  )
}

export async function getStaticProps() {
  const queryClient = new QueryClient()

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}